
import { Product } from '../types';

export const PRODUCTS: Product[] = [
  // Cookware
  { id: 'cw-001', title: 'Non-Stick Ceramic Cookware Set (10-Piece)', description: 'Upgrade your kitchen with this durable and versatile ceramic cookware set. Eco-friendly, non-toxic, and designed for even heat distribution.', features: ['PFOA-free ceramic non-stick', 'Oven safe up to 400°F', 'Stay-cool handles', 'Dishwasher safe'], price: 149.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-001/600/600' },
  { id: 'cw-002', title: 'Pre-Seasoned Cast Iron Skillet (12-Inch)', description: 'A kitchen workhorse. Perfect for searing, sautéing, baking, and frying. Gets better with every use.', features: ['Superior heat retention', 'Ready to use', 'Durable and long-lasting', 'Suitable for all cooktops'], price: 39.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-002/600/600' },
  { id: 'cw-003', title: 'Stainless Steel Saucepan with Lid (3-Quart)', description: 'An essential for any kitchen, this saucepan is perfect for sauces, boiling pasta, or reheating soups.', features: ['5-ply bonded construction', 'Even heat distribution', 'Engraved measurement markings', 'Tight-fitting lid'], price: 79.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-003/600/600' },
  { id: 'cw-004', title: 'Enameled Cast Iron Dutch Oven (5.5-Quart)', description: 'From slow-cooking stews to baking artisan bread, this Dutch oven delivers exceptional results with its superior heat distribution and retention.', features: ['Vibrant enamel finish resists chipping', 'Self-basting lid', 'Large ergonomic handles', 'Oven safe to 500°F'], price: 129.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-004/600/600' },
  { id: 'cw-005', title: 'Hard-Anodized Nonstick Fry Pan Set (8" & 10")', description: 'Everyday essentials for flawless frying and sautéing. The hard-anodized aluminum construction ensures quick, even heating.', features: ['Triple-layer nonstick surface', 'Durable construction', 'Comfortable grip handles', 'Metal utensil safe'], price: 59.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-005/600/600' },
  { id: 'cw-006', title: 'Copper Core 7-Piece Cookware Set', description: 'Experience professional-level control and precision with this copper core cookware set, designed for discerning home chefs.', features: ['5-ply construction with copper core', 'Unmatched heat conductivity', 'Polished stainless steel finish', 'Flared rims for drip-free pouring'], price: 499.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-006/600/600' },

  // Kitchen Tools
  { id: 'kt-001', title: 'Professional Chef\'s Knife (8-Inch)', description: 'The most important tool in your kitchen. High-carbon German steel for precision and durability.', features: ['Full tang construction', 'Ergonomic handle', 'Razor-sharp edge', 'Perfectly balanced'], price: 89.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-001/600/600' },
  { id: 'kt-002', title: 'Silicone Spatula Set (4-Piece)', description: 'Heat resistant and flexible, these spatulas are perfect for scraping, mixing, and folding.', features: ['Heat resistant up to 600°F', 'BPA-free silicone', 'One-piece design for easy cleaning', 'Non-scratch for non-stick pans'], price: 19.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-002/600/600' },
  { id: 'kt-003', title: 'Digital Kitchen Scale', description: 'Achieve perfect results in your baking and cooking with precise measurements.', features: ['Measures in grams, ounces, pounds', 'Tare function', 'Easy-to-read LCD display', 'Slim and stylish design'], price: 24.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-003/600/600' },
  { id: 'kt-004', title: 'Bamboo Cutting Board Set (3 Sizes)', description: 'Durable, eco-friendly, and gentle on your knives. This set has you covered for all chopping needs.', features: ['Made from sustainable bamboo', 'Juice grooves to prevent messes', 'Reversible for double the use', 'Easy to clean'], price: 29.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-004/600/600' },
  { id: 'kt-005', title: 'Stainless Steel Measuring Cups & Spoons', description: 'Elegant and accurate, these measuring tools will last a lifetime with their durable, one-piece construction.', features: ['Engraved measurements won\'t fade', 'Nesting design for easy storage', 'Dishwasher safe', 'Heavy-duty stainless steel'], price: 34.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-005/600/600' },
  { id: 'kt-006', title: 'Garlic Press and Peeler Set', description: 'Effortlessly mince garlic without the mess or odor. The included silicone peeler makes prep a breeze.', features: ['Ergonomic design', 'Easy to clean stainless steel', 'Mince unpeeled cloves', 'Dishwasher safe'], price: 17.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-006/600/600' },
  { id: 'kt-007', title: 'Box Grater with Storage Container', description: 'A versatile 4-sided grater for coarse, medium, and fine grating, plus a slicing side. Includes a catch container.', features: ['4 grating surfaces', 'Non-slip base', 'Includes storage container with lid', 'Surgical-grade stainless steel blades'], price: 22.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-007/600/600' },
  { id: 'kt-008', title: 'Immersion Hand Blender', description: 'Blend smoothies, soups, and sauces directly in your pot or cup. Powerful and easy to use.', features: ['Variable speed control', 'Detachable blending shaft', 'Includes whisk and chopper attachments', 'Ergonomic grip'], price: 49.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-008/600/600' },
  
  // Storage
  { id: 'st-001', title: 'Airtight Glass Food Storage Containers (10-Piece Set)', description: 'Keep your food fresh longer with these leak-proof glass containers. Perfect for meal prep and leftovers.', features: ['BPA-free locking lids', 'Oven, microwave, and freezer safe', 'Stain and odor resistant glass', 'Stackable design'], price: 45.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-001/600/600' },
  { id: 'st-002', title: 'Expandable Pantry Shelf Organizer', description: 'Maximize your cabinet space and easily see all your items. Adjusts to fit your pantry perfectly.', features: ['Adjustable width', 'Durable steel construction', 'Non-slip feet', 'Creates two levels of storage'], price: 25.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-002/600/600' },
  { id: 'st-003', title: 'Reusable Silicone Food Storage Bags (Set of 4)', description: 'An eco-friendly alternative to disposable plastic bags. Perfect for snacks, marinades, and sous vide.', features: ['Leak-proof pinch-lock seal', 'Dishwasher and microwave safe', 'Freezer friendly', 'BPA-free food-grade silicone'], price: 32.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-003/600/600' },
  { id: 'st-004', title: 'Wall-Mounted Magnetic Knife Strip', description: 'Safely and stylishly store your knives while freeing up counter space. Features a powerful, continuous magnet.', features: ['Powerful neodymium magnets', 'Sleek wood or stainless steel finish', 'Easy to install', 'Holds knives and other metal tools securely'], price: 29.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-004/600/600' },
  { id: 'st-005', title: 'Stackable Can Rack Organizer', description: 'Organize your pantry by storing up to 36 cans. The angled shelves make it easy to grab what you need.', features: ['Holds up to 36 cans', 'Sturdy steel construction', 'Adjustable dividers', 'Easy assembly'], price: 28.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-005/600/600' },
  { id: 'st-006', title: 'Clear Pantry Organizer Bins (Set of 6)', description: 'Bring order to your pantry, fridge, or cabinets. The clear design lets you see contents at a glance.', features: ['Made of durable, shatter-resistant plastic', 'Built-in handles for easy transport', 'Stackable to save space', 'BPA-free'], price: 39.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-006/600/600' },
  { id: 'st-007', title: 'Under Sink Expandable Organizer', description: 'Tame the clutter under your kitchen or bathroom sink with this customizable, two-tier shelf.', features: ['Expandable rails fit any cabinet', 'Adjustable shelf height', 'Removable panels accommodate pipes', 'Sturdy metal and plastic construction'], price: 34.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-007/600/600' },
  { id: 'st-008', title: 'Bread Box for Kitchen Countertop', description: 'Keep your bread fresh and your counter tidy with this stylish and spacious bread box.', features: ['Large capacity stores 2+ loaves', 'Eco-friendly bamboo lid doubles as a cutting board', 'Ventilation holes for air circulation', 'Durable metal body'], price: 37.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-008/600/600' },

  // Home Décor
  { id: 'hd-001', title: 'Ceramic Planter Pots with Drainage (Set of 3)', description: 'Add a touch of modern elegance to your home with these minimalist ceramic planters. Perfect for succulents and small plants.', features: ['Includes drainage hole and plug', 'Modern matte finish', 'Three different sizes', 'Perfect for indoor use'], price: 27.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-001/600/600' },
  { id: 'hd-002', title: 'Linen Blend Throw Pillow Covers (Set of 2)', description: 'Instantly update your living room or bedroom with these soft, textured pillow covers.', features: ['High-quality linen blend fabric', 'Hidden zipper closure', 'Available in multiple colors', 'Machine washable'], price: 24.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-002/600/600' },
  { id: 'hd-003', title: 'Acacia Wood Serving Tray with Handles', description: 'A beautiful and functional piece for serving drinks, appetizers, or as a decorative centerpiece.', features: ['Made from rich acacia wood', 'Elegant metal handles', 'Raised edges to prevent spills', 'Versatile and stylish'], price: 35.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-003/600/600' },
  { id: 'hd-004', title: 'Minimalist Wall Clock (12-Inch)', description: 'A silent, non-ticking wall clock that combines modern design with functionality.', features: ['Silent sweep movement', 'Easy-to-read numbers', 'Sleek and simple design', 'Battery operated'], price: 29.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-004/600/600' },
  { id: 'hd-005', title: 'Woven Cotton Rope Storage Basket', description: 'A stylish solution for storing blankets, toys, or laundry. Soft yet sturdy, with convenient handles.', features: ['Made from natural cotton rope', 'Two easy-grip handles', 'Soft and safe for kids', 'Collapsible for easy storage'], price: 26.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-005/600/600' },
  { id: 'hd-006', title: 'Set of 4 Absorbent Ceramic Coasters', description: 'Protect your furniture in style with these highly absorbent ceramic coasters with a non-slip cork base.', features: ['Absorbs condensation quickly', 'Beautiful modern patterns', 'Cork bottom prevents scratches', 'Comes with a metal holder'], price: 18.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-006/600/600' },
  
  // Cleaning Essentials
  { id: 'ce-001', title: 'Microfiber Cleaning Cloths (12-Pack)', description: 'Ultra-soft, non-abrasive cloths that trap dust and grime without chemicals. Perfect for all surfaces.', features: ['Highly absorbent and quick-drying', 'Lint and streak-free', 'Reusable and machine washable', 'Multi-color pack for different tasks'], price: 15.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-001/600/600' },
  { id: 'ce-002', title: 'Eco-Friendly Dish Brush with Replaceable Head', description: 'Scrub effectively and sustainably. This brush features a bamboo handle and tough, plant-based bristles.', features: ['Sustainable bamboo handle', 'Replaceable brush head to reduce waste', 'Tough bristles for baked-on food', 'Built-in scraper'], price: 12.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-002/600/600' },
  { id: 'ce-003', title: 'Slim Step-On Trash Can (10 Gallon)', description: 'A sleek and space-saving trash can with a quiet, slow-close lid. The fingerprint-proof finish stays clean.', features: ['Slim profile for tight spaces', 'Durable steel pedal', 'Removable inner bucket', 'Fingerprint-proof stainless steel'], price: 79.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-003/600/600' },
  { id: 'ce-004', title: 'Spray Mop for Floor Cleaning', description: 'A lightweight and convenient way to clean hard floors. The refillable bottle lets you use your own cleaning solution.', features: ['360-degree rotating head', 'Refillable bottle', 'Includes 3 reusable microfiber pads', 'One-handed trigger operation'], price: 34.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-004/600/600' },
  { id: 'ce-005', title: 'Swedish Dishcloths (10-Pack)', description: 'The sustainable paper towel alternative. Super absorbent, biodegradable, and quick-drying.', features: ['Absorbs 20x its weight', 'Reusable and machine washable', 'Compostable', 'Made from cellulose and cotton'], price: 19.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-005/600/600' },
  { id: 'ce-006', title: 'Extendable Tub and Tile Scrubber', description: 'Clean your bathroom without bending or kneeling. The long handle extends to reach high and low spots with ease.', features: ['Handle extends from 26 to 42 inches', 'Pivoting head for corners', 'Tough, antimicrobial bristles', 'Lightweight and durable'], price: 23.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-006/600/600' },

  // More Products
  { id: 'cw-007', title: 'Grill Pan for Stovetop', description: 'Get perfect grill marks indoors. This cast iron grill pan is ideal for steaks, chicken, and vegetables.', features: ['Deep ridges for authentic grill marks', 'Pour spouts for easy draining', 'Pre-seasoned and ready to use', 'Works on all cooktops'], price: 35.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-007/600/600' },
  { id: 'kt-009', title: 'Salad Spinner', description: 'Enjoy crisp, dry salads every time. Easy one-handed pump operation and a non-slip base.', features: ['One-handed pump and brake button', 'Bowl doubles as a serving dish', 'Basket can be used as a colander', 'Dishwasher safe'], price: 29.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-009/600/600' },
  { id: 'st-009', title: 'Expandable Drawer Organizer for Utensils', description: 'Customize your drawer storage. This bamboo organizer expands to fit perfectly and has multiple compartments.', features: ['Adjusts from 6 to 8 compartments', 'Made from sustainable bamboo', 'Fits most standard drawers', 'Keeps utensils neat and tidy'], price: 29.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-009/600/600' },
  { id: 'hd-007', title: 'Aromatherapy Essential Oil Diffuser', description: 'Create a calming atmosphere with this ultrasonic diffuser. Features multiple mist modes and a 7-color LED light.', features: ['400ml water capacity', 'Whisper-quiet operation', 'Auto shut-off function', '7-color ambient light'], price: 39.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-007/600/600' },
  { id: 'ce-007', title: 'Over-the-Sink Dish Drying Rack', description: 'Save counter space with this roll-up drying rack. Perfect for rinsing produce and drying dishes.', features: ['Rolls up for easy storage', 'Heat-resistant silicone-coated steel', 'Non-slip and durable', 'Dishwasher safe'], price: 21.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-007/600/600' },
  { id: 'cw-008', title: 'Wok with Lid and Spatula (12-inch)', description: 'Master stir-frying with this carbon steel wok. Heats quickly and evenly for authentic results.', features: ['Durable carbon steel construction', 'Flat bottom for stability', 'Includes wooden lid and spatula', 'Helper handle for easy lifting'], price: 49.99, category: 'Cookware', imageUrl: 'https://picsum.photos/seed/cw-008/600/600' },
  { id: 'kt-010', title: 'Mandoline Slicer with 5 Blades', description: 'Achieve perfectly uniform slices every time. Adjustable thickness and multiple blades for versatile cutting.', features: ['5 interchangeable stainless steel blades', 'Adjustable thickness settings', 'Safety food holder included', 'Foldable legs for compact storage'], price: 39.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-010/600/600' },
  { id: 'st-010', title: 'Vertical Pot and Pan Lid Organizer Rack', description: 'Stop searching for the right lid. This rack keeps your cookware organized and accessible in your cabinet.', features: ['Stores up to 5 pans or lids', 'Can be used vertically or horizontally', 'Non-scratch coating protects cookware', 'Sturdy steel construction'], price: 19.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-010/600/600' },
  { id: 'hd-008', title: 'Chunky Knit Throw Blanket', description: 'Cozy up with this incredibly soft and stylish chunky knit blanket. A beautiful accent for your sofa or bed.', features: ['Hand-knitted look and feel', 'Breathable yet warm chenille fabric', 'Hypoallergenic and shed-free', 'Large size for cuddling'], price: 69.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-008/600/600' },
  { id: 'ce-008', title: 'Reusable Wool Dryer Balls (6-Pack)', description: 'A natural fabric softener that shortens drying time and reduces wrinkles. An eco-friendly alternative to dryer sheets.', features: ['Made from 100% New Zealand wool', 'Reduces static cling', 'Lasts for over 1000 loads', 'Chemical-free and hypoallergenic'], price: 16.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-008/600/600' },
  { id: 'kt-011', title: 'Electric Kettle with Temperature Control', description: 'Boil water faster and safer. Perfect for tea lovers, with preset temperature settings for the perfect brew.', features: ['6 preset temperature settings', '1.7-liter capacity', 'Keep warm function', 'Boil-dry protection'], price: 59.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-011/600/600' },
  { id: 'st-011', title: 'Spice Rack Organizer with 24 Jars', description: 'This revolving spice rack keeps your favorite spices at your fingertips. Comes with pre-filled jars.', features: ['Revolving stainless steel design', 'Includes 24 glass spice jars', 'Sift-and-pour caps', 'Free spice refills for 5 years'], price: 49.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-011/600/600' },
  { id: 'hd-009', title: 'Floating Wall Shelves (Set of 3)', description: 'Display photos, books, and decor with these modern floating shelves. A simple way to add character to any wall.', features: ['Minimalist design', 'Easy to install with included hardware', 'Made of durable MDF wood', 'Three different lengths for creative arrangements'], price: 34.99, category: 'Home Décor', imageUrl: 'https://picsum.photos/seed/hd-009/600/600' },
  { id: 'kt-012', title: 'Cold Brew Coffee Maker (1 Quart)', description: 'Make smooth, delicious cold brew coffee at home. Simple to use and fits in most refrigerator doors.', features: ['Durable borosilicate glass pitcher', 'Fine-mesh stainless steel filter', 'Airtight lid keeps coffee fresh', 'Easy to clean'], price: 27.99, category: 'Kitchen Tools', imageUrl: 'https://picsum.photos/seed/kt-012/600/600' },
  { id: 'ce-009', title: 'Grout and Corner Scrubber Brush Set', description: 'Tackle tough grime in tile grout, corners, and tracks. Ergonomic handles provide a comfortable, powerful grip.', features: ['Stiff bristles for deep cleaning', 'Two brushes with unique shapes', 'Comfortable non-slip handles', 'Durable and long-lasting'], price: 12.99, category: 'Cleaning Essentials', imageUrl: 'https://picsum.photos/seed/ce-009/600/600' },
  { id: 'st-012', title: 'Eco-Friendly Glass Water Bottle with Silicone Sleeve', description: 'Stay hydrated on the go with this stylish and reusable glass bottle. The silicone sleeve provides grip and protection.', features: ['Made from high-quality borosilicate glass', 'Protective non-slip silicone sleeve', 'Leak-proof bamboo lid', 'BPA-free'], price: 19.99, category: 'Storage', imageUrl: 'https://picsum.photos/seed/st-012/600/600' },
];
